Added VoiceOver localization for the compose placeholder
parley-messaging/ios-library pull request #179
Opened 2024-11-06 15:17 UTC by martijnvdwal

2024-11-14 08:15 UTC, martijnvdwal commented
fixes #170

2024-11-14 09:39 UTC, alexkok requested changes

2024-11-14 09:39 UTC, alexkok commented on Sources/Parley/Views/ParleyComposeView/ParleyComposeView.swift
> +            textView.accessibilityLabel = placeholderVoiceOver ?? placeholder
Shouldn't we just do a `replace("...", "")`?

Introducing a new string doesn't feel needed for this one

2024-11-14 12:57 UTC, alexkok commented on Sources/Parley/Views/ParleyComposeView/ParleyComposeView.swift
> +            textView.accessibilityLabel = placeholderVoiceOver ?? placeholder
Nevermind

2024-11-14 12:58 UTC, merged

2025-01-17 08:37 UTC, alexkok commented
Released in [4.2.4](https://github.com/parley-messaging/ios-library/releases/tag/4.2.4) 🚀