Added messages manager tests
parley-messaging/ios-library pull request #45
Opened 2023-10-05 14:28 UTC by martijnvdwal

2023-10-05 15:32 UTC, alexkok requested changes

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testTwoMessagesOnDifferentDaysAreSeparatedByDateIndicators() {
Test naming conventions vary in this file. Usually they could be formatted somewhat like: "Test <subject> Should <result> When <conditions>".

So in this case, could be named something like `testTwoMessages_ShouldBeSeparatedByDate_WhenOnDifferentDays()`.

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        XCTAssertEqual(messagesManager.messages[4].type, .user, "Today message should be from the user.")
Nice test, a very important one for Parley, verifying the date messages implementation.

_(Formatting the date itself belongs to its own TestSuit, so perfectly excluded here)_

_P.S.: Nice test values 🙂_

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        XCTAssertEqual(indexPaths[0].section, 0, "Typing message should be the forth index.")
Typo: fourth*

_(multiple places, find and replace)_

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        XCTAssertEqual(indexPaths.count, 1, "Adding Typing indicator should only add a single IndexPath.")
Duplicate test check unneeded

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testAddingMessageWhileAgentIsTying() {
Important test case as well 👍

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        guard let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: today) else { return nil }
Better to throw instead of `nil`, yesterday should in no case be unknown in these tests

2023-10-05 15:32 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        XCTAssertNil(messagesManager.lastSentMessage, "Message should not be considered as being sent.")
👍 Very first flow most users will be in

2023-10-06 11:26 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        Parley.shared.dataSource = dataSource
Oh yeah, agree.
Nice catch 👍

2023-10-06 11:29 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        guard let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: today) else { return nil }
Perfect! ✅

2023-10-06 11:29 UTC, martijnvdwal commented on Source/ParleyTests/MessagesManagerTests.swift
> +        messagesManager.loadCachedData()
Your're right it seems I did miss this important test case. It has been added in the new commit.

2023-10-06 11:30 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +        messagesManager.loadCachedData()
Seen! Yes, this makes it more complete 👍

2023-10-06 11:37 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testMessageManager_ShouldBeCorrectlyConfigured_WhenStartingTheMessagesMannagerWithAMessageCollection() {
In the `when` we already know it's about the messages manager, therefore, we can shorten the name:

Something like: 
`testMessageManager_ShouldBeCorrectlyConfigured_WhenStartingWithAMessageCollection`

2023-10-06 11:37 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testTwoMessagesOnDifferentDays_ShouldBeSeparatedByDateIndicators_WhenMessagesAreOnDifferentDays() throws {
the component name can be just `testTwoMessages` since 'onDifferentDays' is a "when"-reason

2023-10-06 11:37 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testAddTypingIndicator_ShouldBeIgnored_WhenTryingToAddItTwice() {
component shouldn't have `Add` (can be omitted here since its part of the "when" part)

2023-10-06 11:37 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testRemoveTypingIndicator_ShouldReturnNil_WhenTryingToRemoveANonExistentTypingIndicator() {
Same with "remove" here

2023-10-06 11:37 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testAddUserMessage_ShouldRetainCorrectOrder_WhenAgentIsTying() {
This would be more a `testUserMessage_ShouldBeAddedAfterTyping_WhenAgentIsTyping`

2023-10-06 11:39 UTC, alexkok commented on Source/ParleyTests/MessagesManagerTests.swift
> +    func testTwoMessagesOnDifferentDaysAreSeparatedByDateIndicators() {
Much cleaner indeed! Can be improved slightly (see newly added comments), but they are correct yes.

2023-10-12 11:20 UTC, alexkok approved these changes

2023-10-12 11:20 UTC, merged